meta:
  config_source: 'env'
  file_system_type: 'blob'
file_system:
  account_name: 'osci_blob_account_name'
  account_key: 'osci_blob_account_key'
areas:
  landing:
    container: 'osci_landing_container'
  staging:
    container: 'osci_staging_container'
  public:
    container: 'osci_public_container'
bq:
  project: 'osci_bq_project'
  secret: 'osci_bq_secret'